In [1]:
import pandas as pd

# Specify the path to your CSV file
csv_file_path = r"C:\Users\LENOVO\Downloads\KENYAN COUNTY_GEO\Landjob_2024.csv"

df = pd.read_csv(csv_file_path, low_memory=False)

In [2]:
df.head()

,id,created_at,updated_at,source,activity_id,jobStartTime,jobEndTime,eventType,area,distance,...,operator_id,state,trip_id,user_id,location_id,fuel_refuelled,fuel_siphoned,net_fuel_consumed,approved,deleted_at
0,1154342,2024-06-11 15:46:24.884924+00:00,2024-06-11 19:03:26.544440+00:00,20,932756,2024-06-11 11:18:15+00:00,2024-06-11 14:08:25+00:00,dbs,0.642436,0.053252,...,NaN,1.0,NaN,7840.0,639.0,0.0,0.0,0.0,True,NaN
1,1000280,2024-04-12 19:56:51.858323+00:00,2024-04-12 19:56:51.858345+00:00,30,871290,2024-04-12 09:12:58+00:00,2024-04-12 18:07:32+00:00,NaN,2.789345,34.619896,...,NaN,1.0,NaN,7840.0,458.0,0.0,0.0,0.0,True,NaN
2,1000284,2024-04-12 19:57:17.567992+00:00,2024-04-12 19:57:17.568014+00:00,30,871400,2024-04-12 09:05:19+00:00,2024-04-12 09:20:20+00:00,NaN,0.062322,0.328432,...,NaN,1.0,NaN,26.0,557.0,0.0,0.0,0.0,True,NaN
3,1000285,2024-04-12 19:57:22.685770+00:00,2024-04-12 19:57:22.685789+00:00,30,871400,2024-04-12 08:34:59+00:00,2024-04-12 09:02:19+00:00,NaN,0.042772,0.299703,...,NaN,1.0,NaN,26.0,557.0,0.0,0.0,0.0,True,NaN
4,1000286,2024-04-12 19:57:27.559368+00:00,2024-04-12 19:57:27.559386+00:00,30,871400,2024-04-12 09:27:43+00:00,2024-04-12 09:40:57+00:00,NaN,0.033859,0.431969,...,NaN,1.0,NaN,26.0,557.0,0.0,0.0,0.0,True,NaN

In [3]:
# Display the first few rows of the 'polygon' column
print(df['polygon'].head())

0    0103000020E61000000100000017000000E0BEC62B1043...
1    0103000020E61000000100000027000000B80375CAA3ED...
2    0103000020E610000001000000070000006286C613417A...
3    0103000020E61000000100000006000000AEEFC341427A...
4    0103000020E610000001000000070000005CC98E8D407A...
Name: polygon, dtype: object

In [4]:
from shapely.wkb import loads
from shapely.geometry import mapping, MultiPolygon, Polygon
import pandas as pd

def wkb_to_multipolygon_geojson(wkb_string):
    try:
        # Ensure the WKB string has an even length
        if len(wkb_string) % 2 != 0:
            raise ValueError("WKB string length is not even, indicating possible truncation.")
        
        # Convert hexadecimal string to bytes
        byte_data = bytes.fromhex(wkb_string)
        
        # Load geometry from bytes
        geometry = loads(byte_data, hex=False)  # hex=False means input is a byte array
        
        # Convert Polygon to MultiPolygon if necessary
        if isinstance(geometry, Polygon):
            geometry = MultiPolygon([geometry])
        
        # Convert to GeoJSON format
        geojson = mapping(geometry)
        return geojson
    except Exception as e:
        print(f"Error processing WKB string '{wkb_string}': {e}")
        return None  # Return None or an appropriate value indicating failure


df = pd.read_csv(csv_file_path, low_memory=False)

# Convert WKB to MultiPolygon GeoJSON
df['polygon_geojson'] = df['polygon'].apply(wkb_to_multipolygon_geojson)

# Display the first few rows of the 'polygon_geojson' column
df['polygon_geojson'].head()

Error processing WKB string '0103000020E61000000100000008000000268C6665FB3E414088A1D5C9198AC3BFEA25C632FD3E4140209BE447FC8AC3BFDEAB5626FC3E4140100533A6608DC3BFEA25C632FD3E4140DDB1D826158DC3BFF59F353FFE3E4140D63BDC0E0D8BC3BF520C': ParseException: Input buffer is smaller than requested object size

0    {'type': 'MultiPolygon', 'coordinates': [(((36...
1    {'type': 'MultiPolygon', 'coordinates': [(((39...
2    {'type': 'MultiPolygon', 'coordinates': [(((34...
3    {'type': 'MultiPolygon', 'coordinates': [(((34...
4    {'type': 'MultiPolygon', 'coordinates': [(((34...
Name: polygon_geojson, dtype: object

In [5]:
df['polygon_geojson'].tail()

37201    {'type': 'MultiPolygon', 'coordinates': [(((34...
37202    {'type': 'MultiPolygon', 'coordinates': [(((35...
37203    {'type': 'MultiPolygon', 'coordinates': [(((35...
37204    {'type': 'MultiPolygon', 'coordinates': [(((34...
37205                                                 None
Name: polygon_geojson, dtype: object

In [6]:
df.columns

Index(['id', 'created_at', 'updated_at', 'source', 'activity_id',
       'jobStartTime', 'jobEndTime', 'eventType', 'area', 'distance',
       'duration', 'jobStartLatitude', 'jobStartLongitude', 'jobEndLatitude',
       'jobEndLongitude', 'jobUid', 'polygon', 'crop_id', 'implement_id',
       'metadata', 'operator_id', 'state', 'trip_id', 'user_id', 'location_id',
       'fuel_refuelled', 'fuel_siphoned', 'net_fuel_consumed', 'approved',
       'deleted_at', 'polygon_geojson'],
      dtype='object')

In [7]:
df_new = df.drop(columns=['polygon'])

In [9]:
df_new.columns

Index(['id', 'created_at', 'updated_at', 'source', 'activity_id',
       'jobStartTime', 'jobEndTime', 'eventType', 'area', 'distance',
       'duration', 'jobStartLatitude', 'jobStartLongitude', 'jobEndLatitude',
       'jobEndLongitude', 'jobUid', 'crop_id', 'implement_id', 'metadata',
       'operator_id', 'state', 'trip_id', 'user_id', 'location_id',
       'fuel_refuelled', 'fuel_siphoned', 'net_fuel_consumed', 'approved',
       'deleted_at', 'polygon_geojson'],
      dtype='object')

In [11]:
df_new

,id,created_at,updated_at,source,activity_id,jobStartTime,jobEndTime,eventType,area,distance,...,state,trip_id,user_id,location_id,fuel_refuelled,fuel_siphoned,net_fuel_consumed,approved,deleted_at,polygon_geojson
0,1154342,2024-06-11 15:46:24.884924+00:00,2024-06-11 19:03:26.544440+00:00,20,932756,2024-06-11 11:18:15+00:00,2024-06-11 14:08:25+00:00,dbs,0.642436,0.053252,...,1.0,NaN,7840.0,639.0,0.0,0.0,0.0,True,NaN,"{'type': 'MultiPolygon', 'coordinates': [(((36..."
1,1000280,2024-04-12 19:56:51.858323+00:00,2024-04-12 19:56:51.858345+00:00,30,871290,2024-04-12 09:12:58+00:00,2024-04-12 18:07:32+00:00,NaN,2.789345,34.619896,...,1.0,NaN,7840.0,458.0,0.0,0.0,0.0,True,NaN,"{'type': 'MultiPolygon', 'coordinates': [(((39..."
2,1000284,2024-04-12 19:57:17.567992+00:00,2024-04-12 19:57:17.568014+00:00,30,871400,2024-04-12 09:05:19+00:00,2024-04-12 09:20:20+00:00,NaN,0.062322,0.328432,...,1.0,NaN,26.0,557.0,0.0,0.0,0.0,True,NaN,"{'type': 'MultiPolygon', 'coordinates': [(((34..."
3,1000285,2024-04-12 19:57:22.685770+00:00,2024-04-12 19:57:22.685789+00:00,30,871400,2024-04-12 08:34:59+00:00,2024-04-12 09:02:19+00:00,NaN,0.042772,0.299703,...,1.0,NaN,26.0,557.0,0.0,0.0,0.0,True,NaN,"{'type': 'MultiPolygon', 'coordinates': [(((34..."
4,1000286,2024-04-12 19:57:27.559368+00:00,2024-04-12 19:57:27.559386+00:00,30,871400,2024-04-12 09:27:43+00:00,2024-04-12 09:40:57+00:00,NaN,0.033859,0.431969,...,1.0,NaN,26.0,557.0,0.0,0.0,0.0,True,NaN,"{'type': 'MultiPolygon', 'coordinates': [(((34..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37201,853283,2024-02-13 20:00:17.150905+00:00,2024-02-13 20:00:17.150925+00:00,30,819555,2024-02-13 11:27:56+00:00,2024-02-13 11:32:19+00:00,NaN,0.005252,0.199130,...,1.0,NaN,26.0,549.0,0.0,0.0,0.0,True,NaN,"{'type': 'MultiPolygon', 'coordinates': [(((34..."
37202,854986,2024-02-14 19:50:09.471212+00:00,2024-02-14 19:50:09.471234+00:00,30,820857,2024-02-14 08:59:13+00:00,2024-02-14 09:11:09+00:00,NaN,0.099990,0.346933,...,1.0,NaN,4502.0,1097.0,0.0,0.0,0.0,True,NaN,"{'type': 'MultiPolygon', 'coordinates': [(((35..."
37203,816322,2024-01-09 17:45:12.114549+00:00,2024-01-09 17:45:12.114584+00:00,30,795707,2024-01-09 11:59:06+00:00,2024-01-09 12:19:09+00:00,NaN,0.299702,1.167026,...,1.0,NaN,26.0,1108.0,0.0,0.0,0.0,True,NaN,"{'type': 'MultiPolygon', 'coordinates': [(((35..."
37204,822920,2024-01-16 20:01:35.602984+00:00,2024-01-16 20:01:35.603011+00:00,30,800420,2024-01-16 07:03:25+00:00,2024-01-16 13:40:00+00:00,NaN,0.797925,14.471523,...,1.0,NaN,24.0,1448.0,0.0,0.0,0.0,True,NaN,"{'type': 'MultiPolygon', 'coordinates': [(((34..."
37205,840563,2024-02-03 20:27:13.545991+00:00,2024-02-03 20:27:13.546006+00:00,30,812686,2024-02-03 07:25:50+00:00,2024-02-03 07:33:37+00:00,NaN,0.009102,0.188979,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

In [17]:
import geopandas as gpd
import pandas as pd
from shapely.geometry import shape

# Function to convert GeoJSON to Shapely geometry
def geojson_to_shapely(geojson):
    try:
        if geojson and isinstance(geojson, dict):  # Ensure valid GeoJSON
            return shape(geojson)
    except Exception as e:
        print(f"Error converting GeoJSON to Shapely geometry: {e}")
    return None



# Convert GeoJSON to Shapely geometries
df_new['geometry'] = df_new['polygon_geojson'].apply(geojson_to_shapely)

# Create a GeoDataFrame
geo_df = gpd.GeoDataFrame(df_new, geometry='geometry')

# Save the GeoDataFrame to a GeoJSON file
geo_df.to_file("output.geojson", driver="GeoJSON")

# Display the GeoDataFrame to verify
geo_df.head()

C:\Users\LENOVO\anaconda3\Lib\site-packages\pyogrio\raw.py:698: UserWarning: 'crs' was not provided.  The output dataset will not have projection information defined and may not be usable in other systems.
  warnings.warn(

,id,created_at,updated_at,source,activity_id,jobStartTime,jobEndTime,eventType,area,distance,...,trip_id,user_id,location_id,fuel_refuelled,fuel_siphoned,net_fuel_consumed,approved,deleted_at,polygon_geojson,geometry
0,1154342,2024-06-11 15:46:24.884924+00:00,2024-06-11 19:03:26.544440+00:00,20,932756,2024-06-11 11:18:15+00:00,2024-06-11 14:08:25+00:00,dbs,0.642436,0.053252,...,NaN,7840.0,639.0,0.0,0.0,0.0,True,NaN,"{'type': 'MultiPolygon', 'coordinates': [(((36...","MULTIPOLYGON (((36.52393 0.2295, 36.52399 0.22..."
1,1000280,2024-04-12 19:56:51.858323+00:00,2024-04-12 19:56:51.858345+00:00,30,871290,2024-04-12 09:12:58+00:00,2024-04-12 18:07:32+00:00,NaN,2.789345,34.619896,...,NaN,7840.0,458.0,0.0,0.0,0.0,True,NaN,"{'type': 'MultiPolygon', 'coordinates': [(((39...","MULTIPOLYGON (((39.85656 -3.14884, 39.85664 -3..."
2,1000284,2024-04-12 19:57:17.567992+00:00,2024-04-12 19:57:17.568014+00:00,30,871400,2024-04-12 09:05:19+00:00,2024-04-12 09:20:20+00:00,NaN,0.062322,0.328432,...,NaN,26.0,557.0,0.0,0.0,0.0,True,NaN,"{'type': 'MultiPolygon', 'coordinates': [(((34...","MULTIPOLYGON (((34.95511 -0.18765, 34.95492 -0..."
3,1000285,2024-04-12 19:57:22.685770+00:00,2024-04-12 19:57:22.685789+00:00,30,871400,2024-04-12 08:34:59+00:00,2024-04-12 09:02:19+00:00,NaN,0.042772,0.299703,...,NaN,26.0,557.0,0.0,0.0,0.0,True,NaN,"{'type': 'MultiPolygon', 'coordinates': [(((34...","MULTIPOLYGON (((34.95515 -0.18746, 34.95488 -0..."
4,1000286,2024-04-12 19:57:27.559368+00:00,2024-04-12 19:57:27.559386+00:00,30,871400,2024-04-12 09:27:43+00:00,2024-04-12 09:40:57+00:00,NaN,0.033859,0.431969,...,NaN,26.0,557.0,0.0,0.0,0.0,True,NaN,"{'type': 'MultiPolygon', 'coordinates': [(((34...","MULTIPOLYGON (((34.9551 -0.18734, 34.95479 -0...."